# NOTE: reference doc
# https://santhosh-adiga-u.medium.com/setting-up-a-complete-ci-cd-pipeline-for-react-using-github-actions-9a07613ceded
name: Build and Deploy Checkers

on:
  push:
    branches:
      - master  # or any other branch you want to trigger this workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or the version required by your app

      - name: Install dependencies
        run: |
          cd checkers
          npm install

      - name: Build the app
        run: |
          cd checkers
          npm run build

      # Add deployment steps here, if applicable
      # For example, deploying to GitHub Pages or any other hosting service