# NOTE: reference doc
# https://santhosh-adiga-u.medium.com/setting-up-a-complete-ci-cd-pipeline-for-react-using-github-actions-9a07613ceded
name: CI/CD Pipeline


on:
  pull_request:
    branches: [ master ] # or your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # or your preferred Node.js version

      - name: Install dependencies
        run: |
          cd checkers
          npm install

      - name: Run unit tests
        run: |
          cd checkers
          npm run test
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: |
          cd checkers
          npm install
      
      - name: Start application
        run: |
          cd checkers
          npm start &
        env:
          NODE_ENV: test  # Set environment variables if needed
